### ISSUE TITLE
Usage Regulation and Scheduling

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/gpu-cluster#7]
How do we prevent users from mining bitcoin

**Comment by narendasan** [comment]
https://github.com/dholt/slurm-gpu

**Comment by apache8080** [comment]
Going to close this issue as the plan with the current jupyter notebook app is to package it in conda/snap and allow people to host their own version themselves (e.g. a professor in a classroom) so there is no need for usage regulation and scheduling. We are starting work on building a task runner for the ACM GPU cluster where this will be better suited.
